//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RobynsHandMadeSoapModel", "FK_Product_Detail2Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RobynHandMadeSoap.Product), "Product_Detail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RobynHandMadeSoap.Product_Detail), true)]
[assembly: EdmRelationshipAttribute("RobynsHandMadeSoapModel", "FK_Ingredient2Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RobynHandMadeSoap.Product), "Product_Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RobynHandMadeSoap.Product_Ingredient), true)]
[assembly: EdmRelationshipAttribute("RobynsHandMadeSoapModel", "FK_Product2Category", "Product_Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RobynHandMadeSoap.Product_Categories), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RobynHandMadeSoap.Product), true)]
[assembly: EdmRelationshipAttribute("RobynsHandMadeSoapModel", "FK_Product2Ingredient", "Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RobynHandMadeSoap.Ingredient), "Product_Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RobynHandMadeSoap.Product_Ingredient), true)]
[assembly: EdmRelationshipAttribute("RobynsHandMadeSoapModel", "FK_Stockist2Location", "Stockist_Locations", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RobynHandMadeSoap.Stockist_Locations), "Stockist", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RobynHandMadeSoap.Stockist), true)]

#endregion

namespace RobynHandMadeSoap
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RobynsHandMadeSoapEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RobynsHandMadeSoapEntities object using the connection string found in the 'RobynsHandMadeSoapEntities' section of the application configuration file.
        /// </summary>
        public RobynsHandMadeSoapEntities() : base("name=RobynsHandMadeSoapEntities", "RobynsHandMadeSoapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RobynsHandMadeSoapEntities object.
        /// </summary>
        public RobynsHandMadeSoapEntities(string connectionString) : base(connectionString, "RobynsHandMadeSoapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RobynsHandMadeSoapEntities object.
        /// </summary>
        public RobynsHandMadeSoapEntities(EntityConnection connection) : base(connection, "RobynsHandMadeSoapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<News> News
        {
            get
            {
                if ((_News == null))
                {
                    _News = base.CreateObjectSet<News>("News");
                }
                return _News;
            }
        }
        private ObjectSet<News> _News;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stockist> Stockists
        {
            get
            {
                if ((_Stockists == null))
                {
                    _Stockists = base.CreateObjectSet<Stockist>("Stockists");
                }
                return _Stockists;
            }
        }
        private ObjectSet<Stockist> _Stockists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stockist_Locations> Stockist_Locations
        {
            get
            {
                if ((_Stockist_Locations == null))
                {
                    _Stockist_Locations = base.CreateObjectSet<Stockist_Locations>("Stockist_Locations");
                }
                return _Stockist_Locations;
            }
        }
        private ObjectSet<Stockist_Locations> _Stockist_Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product_Detail> Product_Detail
        {
            get
            {
                if ((_Product_Detail == null))
                {
                    _Product_Detail = base.CreateObjectSet<Product_Detail>("Product_Detail");
                }
                return _Product_Detail;
            }
        }
        private ObjectSet<Product_Detail> _Product_Detail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product_Ingredient> Product_Ingredient
        {
            get
            {
                if ((_Product_Ingredient == null))
                {
                    _Product_Ingredient = base.CreateObjectSet<Product_Ingredient>("Product_Ingredient");
                }
                return _Product_Ingredient;
            }
        }
        private ObjectSet<Product_Ingredient> _Product_Ingredient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product_Categories> Product_Categories
        {
            get
            {
                if ((_Product_Categories == null))
                {
                    _Product_Categories = base.CreateObjectSet<Product_Categories>("Product_Categories");
                }
                return _Product_Categories;
            }
        }
        private ObjectSet<Product_Categories> _Product_Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Access_History> Access_History
        {
            get
            {
                if ((_Access_History == null))
                {
                    _Access_History = base.CreateObjectSet<Access_History>("Access_History");
                }
                return _Access_History;
            }
        }
        private ObjectSet<Access_History> _Access_History;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the News EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stockists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStockists(Stockist stockist)
        {
            base.AddObject("Stockists", stockist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stockist_Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStockist_Locations(Stockist_Locations stockist_Locations)
        {
            base.AddObject("Stockist_Locations", stockist_Locations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product_Detail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct_Detail(Product_Detail product_Detail)
        {
            base.AddObject("Product_Detail", product_Detail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product_Ingredient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct_Ingredient(Product_Ingredient product_Ingredient)
        {
            base.AddObject("Product_Ingredient", product_Ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product_Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct_Categories(Product_Categories product_Categories)
        {
            base.AddObject("Product_Categories", product_Categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Access_History EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccess_History(Access_History access_History)
        {
            base.AddObject("Access_History", access_History);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Access_History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Access_History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Access_History object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Access_History CreateAccess_History(global::System.Int32 id, global::System.DateTime date)
        {
            Access_History access_History = new Access_History();
            access_History.Id = id;
            access_History.Date = date;
            return access_History;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attempted_URL
        {
            get
            {
                return _Attempted_URL;
            }
            set
            {
                OnAttempted_URLChanging(value);
                ReportPropertyChanging("Attempted_URL");
                _Attempted_URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attempted_URL");
                OnAttempted_URLChanged();
            }
        }
        private global::System.String _Attempted_URL;
        partial void OnAttempted_URLChanging(global::System.String value);
        partial void OnAttempted_URLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stage
        {
            get
            {
                return _Stage;
            }
            set
            {
                OnStageChanging(value);
                ReportPropertyChanging("Stage");
                _Stage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stage");
                OnStageChanged();
            }
        }
        private global::System.String _Stage;
        partial void OnStageChanging(global::System.String value);
        partial void OnStageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OACode
        {
            get
            {
                return _OACode;
            }
            set
            {
                OnOACodeChanging(value);
                ReportPropertyChanging("OACode");
                _OACode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OACode");
                OnOACodeChanged();
            }
        }
        private global::System.String _OACode;
        partial void OnOACodeChanging(global::System.String value);
        partial void OnOACodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OAToken
        {
            get
            {
                return _OAToken;
            }
            set
            {
                OnOATokenChanging(value);
                ReportPropertyChanging("OAToken");
                _OAToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OAToken");
                OnOATokenChanged();
            }
        }
        private global::System.String _OAToken;
        partial void OnOATokenChanging(global::System.String value);
        partial void OnOATokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CookieSet
        {
            get
            {
                return _CookieSet;
            }
            set
            {
                OnCookieSetChanging(value);
                ReportPropertyChanging("CookieSet");
                _CookieSet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CookieSet");
                OnCookieSetChanged();
            }
        }
        private global::System.String _CookieSet;
        partial void OnCookieSetChanging(global::System.String value);
        partial void OnCookieSetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CookiePath
        {
            get
            {
                return _CookiePath;
            }
            set
            {
                OnCookiePathChanging(value);
                ReportPropertyChanging("CookiePath");
                _CookiePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CookiePath");
                OnCookiePathChanged();
            }
        }
        private global::System.String _CookiePath;
        partial void OnCookiePathChanging(global::System.String value);
        partial void OnCookiePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResultSF
        {
            get
            {
                return _ResultSF;
            }
            set
            {
                OnResultSFChanging(value);
                ReportPropertyChanging("ResultSF");
                _ResultSF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResultSF");
                OnResultSFChanged();
            }
        }
        private global::System.String _ResultSF;
        partial void OnResultSFChanging(global::System.String value);
        partial void OnResultSFChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 id, global::System.String name, global::System.String description)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.Id = id;
            ingredient.Name = name;
            ingredient.Description = description;
            return ingredient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product2Ingredient", "Product_Ingredient")]
        public EntityCollection<Product_Ingredient> Product_Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product_Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Product_Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product_Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Product_Ingredient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="News")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class News : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new News object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="detail">Initial value of the Detail property.</param>
        public static News CreateNews(global::System.Int32 id, global::System.DateTime date, global::System.String detail)
        {
            News news = new News();
            news.Id = id;
            news.Date = date;
            news.Detail = detail;
            return news;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd MMM yy}", ApplyFormatInEditMode = true)]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImgURL
        {
            get
            {
                return _ImgURL;
            }
            set
            {
                OnImgURLChanging(value);
                ReportPropertyChanging("ImgURL");
                _ImgURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImgURL");
                OnImgURLChanged();
            }
        }
        private global::System.String _ImgURL;
        partial void OnImgURLChanging(global::System.String value);
        partial void OnImgURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateString
        {
            get
            {
                return _DateString;
            }
            set
            {
                OnDateStringChanging(value);
                ReportPropertyChanging("DateString");
                _DateString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DateString");
                OnDateStringChanged();
            }
        }
        private global::System.String _DateString;
        partial void OnDateStringChanging(global::System.String value);
        partial void OnDateStringChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="image_Uri">Initial value of the Image_Uri property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.String name, global::System.String image_Uri, global::System.String description)
        {
            Product product = new Product();
            product.Id = id;
            product.Name = name;
            product.Image_Uri = image_Uri;
            product.Description = description;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [DataType("Image_Uri")]
        public global::System.String Image_Uri
        {
            get
            {
                return _Image_Uri;
            }
            set
            {
                OnImage_UriChanging(value);
                ReportPropertyChanging("Image_Uri");
                _Image_Uri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image_Uri");
                OnImage_UriChanged();
            }
        }
        private global::System.String _Image_Uri;
        partial void OnImage_UriChanging(global::System.String value);
        partial void OnImage_UriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required]
        public Nullable<global::System.Int32> Category_Id
        {
            get
            {
                return _Category_Id;
            }
            set
            {
                OnCategory_IdChanging(value);
                ReportPropertyChanging("Category_Id");
                _Category_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_Id");
                OnCategory_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Category_Id;
        partial void OnCategory_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCategory_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Code
        {
            get
            {
                return _Product_Code;
            }
            set
            {
                OnProduct_CodeChanging(value);
                ReportPropertyChanging("Product_Code");
                _Product_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Code");
                OnProduct_CodeChanged();
            }
        }
        private global::System.String _Product_Code;
        partial void OnProduct_CodeChanging(global::System.String value);
        partial void OnProduct_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PP_Hosted_Button_Id
        {
            get
            {
                return _PP_Hosted_Button_Id;
            }
            set
            {
                OnPP_Hosted_Button_IdChanging(value);
                ReportPropertyChanging("PP_Hosted_Button_Id");
                _PP_Hosted_Button_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PP_Hosted_Button_Id");
                OnPP_Hosted_Button_IdChanged();
            }
        }
        private global::System.String _PP_Hosted_Button_Id;
        partial void OnPP_Hosted_Button_IdChanging(global::System.String value);
        partial void OnPP_Hosted_Button_IdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status_Reason
        {
            get
            {
                return _Status_Reason;
            }
            set
            {
                OnStatus_ReasonChanging(value);
                ReportPropertyChanging("Status_Reason");
                _Status_Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status_Reason");
                OnStatus_ReasonChanged();
            }
        }
        private global::System.String _Status_Reason;
        partial void OnStatus_ReasonChanging(global::System.String value);
        partial void OnStatus_ReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Status_Date
        {
            get
            {
                return _Status_Date;
            }
            set
            {
                OnStatus_DateChanging(value);
                ReportPropertyChanging("Status_Date");
                _Status_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status_Date");
                OnStatus_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Status_Date;
        partial void OnStatus_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnStatus_DateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product_Detail2Product", "Product_Detail")]
        public EntityCollection<Product_Detail> Product_Detail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product_Detail>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product_Detail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product_Detail>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product_Detail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Ingredient2Product", "Product_Ingredient")]
        public EntityCollection<Product_Ingredient> Product_Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product_Ingredient>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product_Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product_Ingredient>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product_Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product2Category", "Product_Categories")]
        public Product_Categories Product_Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product_Categories>("RobynsHandMadeSoapModel.FK_Product2Category", "Product_Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product_Categories>("RobynsHandMadeSoapModel.FK_Product2Category", "Product_Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product_Categories> Product_CategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product_Categories>("RobynsHandMadeSoapModel.FK_Product2Category", "Product_Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product_Categories>("RobynsHandMadeSoapModel.FK_Product2Category", "Product_Categories", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Product_Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product_Categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product_Categories object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Product_Categories CreateProduct_Categories(global::System.Int32 id, global::System.String name)
        {
            Product_Categories product_Categories = new Product_Categories();
            product_Categories.Id = id;
            product_Categories.Name = name;
            return product_Categories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [Required]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image_Uri
        {
            get
            {
                return _Image_Uri;
            }
            set
            {
                OnImage_UriChanging(value);
                ReportPropertyChanging("Image_Uri");
                _Image_Uri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image_Uri");
                OnImage_UriChanged();
            }
        }
        private global::System.String _Image_Uri;
        partial void OnImage_UriChanging(global::System.String value);
        partial void OnImage_UriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status_Reason
        {
            get
            {
                return _Status_Reason;
            }
            set
            {
                OnStatus_ReasonChanging(value);
                ReportPropertyChanging("Status_Reason");
                _Status_Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status_Reason");
                OnStatus_ReasonChanged();
            }
        }
        private global::System.String _Status_Reason;
        partial void OnStatus_ReasonChanging(global::System.String value);
        partial void OnStatus_ReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Status_Date
        {
            get
            {
                return _Status_Date;
            }
            set
            {
                OnStatus_DateChanging(value);
                ReportPropertyChanging("Status_Date");
                _Status_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status_Date");
                OnStatus_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Status_Date;
        partial void OnStatus_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnStatus_DateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product2Category", "Product")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("RobynsHandMadeSoapModel.FK_Product2Category", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("RobynsHandMadeSoapModel.FK_Product2Category", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Product_Detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product_Detail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product_Detail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="effective_Date">Initial value of the Effective_Date property.</param>
        /// <param name="price_Currency_Code">Initial value of the Price_Currency_Code property.</param>
        /// <param name="long_Description">Initial value of the Long_Description property.</param>
        public static Product_Detail CreateProduct_Detail(global::System.Int32 id, global::System.Int32 product_Id, global::System.Decimal price, global::System.DateTime effective_Date, global::System.String price_Currency_Code, global::System.String long_Description)
        {
            Product_Detail product_Detail = new Product_Detail();
            product_Detail.Id = id;
            product_Detail.Product_Id = product_Id;
            product_Detail.Price = price;
            product_Detail.Effective_Date = effective_Date;
            product_Detail.Price_Currency_Code = price_Currency_Code;
            product_Detail.Long_Description = long_Description;
            return product_Detail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                OnProduct_IdChanging(value);
                ReportPropertyChanging("Product_Id");
                _Product_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_Id");
                OnProduct_IdChanged();
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Effective_Date
        {
            get
            {
                return _Effective_Date;
            }
            set
            {
                OnEffective_DateChanging(value);
                ReportPropertyChanging("Effective_Date");
                _Effective_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Effective_Date");
                OnEffective_DateChanged();
            }
        }
        private global::System.DateTime _Effective_Date;
        partial void OnEffective_DateChanging(global::System.DateTime value);
        partial void OnEffective_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Cease_Date
        {
            get
            {
                return _Cease_Date;
            }
            set
            {
                OnCease_DateChanging(value);
                ReportPropertyChanging("Cease_Date");
                _Cease_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cease_Date");
                OnCease_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Cease_Date;
        partial void OnCease_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnCease_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Price_Currency_Code
        {
            get
            {
                return _Price_Currency_Code;
            }
            set
            {
                OnPrice_Currency_CodeChanging(value);
                ReportPropertyChanging("Price_Currency_Code");
                _Price_Currency_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Price_Currency_Code");
                OnPrice_Currency_CodeChanged();
            }
        }
        private global::System.String _Price_Currency_Code;
        partial void OnPrice_Currency_CodeChanging(global::System.String value);
        partial void OnPrice_Currency_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Long_Description
        {
            get
            {
                return _Long_Description;
            }
            set
            {
                OnLong_DescriptionChanging(value);
                ReportPropertyChanging("Long_Description");
                _Long_Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Long_Description");
                OnLong_DescriptionChanged();
            }
        }
        private global::System.String _Long_Description;
        partial void OnLong_DescriptionChanging(global::System.String value);
        partial void OnLong_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Stock_Quantity
        {
            get
            {
                return _Stock_Quantity;
            }
            set
            {
                OnStock_QuantityChanging(value);
                ReportPropertyChanging("Stock_Quantity");
                _Stock_Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock_Quantity");
                OnStock_QuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Stock_Quantity;
        partial void OnStock_QuantityChanging(Nullable<global::System.Int32> value);
        partial void OnStock_QuantityChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product_Detail2Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Product_Detail2Product", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Product_Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product_Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product_Ingredient object.
        /// </summary>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        /// <param name="ingredient_Id">Initial value of the Ingredient_Id property.</param>
        /// <param name="effective_Date">Initial value of the Effective_Date property.</param>
        /// <param name="cease_Date">Initial value of the Cease_Date property.</param>
        public static Product_Ingredient CreateProduct_Ingredient(global::System.Int32 product_Id, global::System.Int32 ingredient_Id, global::System.DateTime effective_Date, global::System.DateTime cease_Date)
        {
            Product_Ingredient product_Ingredient = new Product_Ingredient();
            product_Ingredient.Product_Id = product_Id;
            product_Ingredient.Ingredient_Id = ingredient_Id;
            product_Ingredient.Effective_Date = effective_Date;
            product_Ingredient.Cease_Date = cease_Date;
            return product_Ingredient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                if (_Product_Id != value)
                {
                    OnProduct_IdChanging(value);
                    ReportPropertyChanging("Product_Id");
                    _Product_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_Id");
                    OnProduct_IdChanged();
                }
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ingredient_Id
        {
            get
            {
                return _Ingredient_Id;
            }
            set
            {
                if (_Ingredient_Id != value)
                {
                    OnIngredient_IdChanging(value);
                    ReportPropertyChanging("Ingredient_Id");
                    _Ingredient_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ingredient_Id");
                    OnIngredient_IdChanged();
                }
            }
        }
        private global::System.Int32 _Ingredient_Id;
        partial void OnIngredient_IdChanging(global::System.Int32 value);
        partial void OnIngredient_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Effective_Date
        {
            get
            {
                return _Effective_Date;
            }
            set
            {
                OnEffective_DateChanging(value);
                ReportPropertyChanging("Effective_Date");
                _Effective_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Effective_Date");
                OnEffective_DateChanged();
            }
        }
        private global::System.DateTime _Effective_Date;
        partial void OnEffective_DateChanging(global::System.DateTime value);
        partial void OnEffective_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Cease_Date
        {
            get
            {
                return _Cease_Date;
            }
            set
            {
                OnCease_DateChanging(value);
                ReportPropertyChanging("Cease_Date");
                _Cease_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cease_Date");
                OnCease_DateChanged();
            }
        }
        private global::System.DateTime _Cease_Date;
        partial void OnCease_DateChanging(global::System.DateTime value);
        partial void OnCease_DateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Ingredient2Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("RobynsHandMadeSoapModel.FK_Ingredient2Product", "Product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Product2Ingredient", "Ingredient")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Ingredient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Ingredient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("RobynsHandMadeSoapModel.FK_Product2Ingredient", "Ingredient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Stockist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stockist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stockist object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="location_Id">Initial value of the Location_Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="effective_Date">Initial value of the Effective_Date property.</param>
        public static Stockist CreateStockist(global::System.Int32 id, global::System.Int32 location_Id, global::System.String name, global::System.DateTime effective_Date)
        {
            Stockist stockist = new Stockist();
            stockist.Id = id;
            stockist.Location_Id = location_Id;
            stockist.Name = name;
            stockist.Effective_Date = effective_Date;
            return stockist;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Location_Id
        {
            get
            {
                return _Location_Id;
            }
            set
            {
                OnLocation_IdChanging(value);
                ReportPropertyChanging("Location_Id");
                _Location_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Location_Id");
                OnLocation_IdChanged();
            }
        }
        private global::System.Int32 _Location_Id;
        partial void OnLocation_IdChanging(global::System.Int32 value);
        partial void OnLocation_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GPS_Lat
        {
            get
            {
                return _GPS_Lat;
            }
            set
            {
                OnGPS_LatChanging(value);
                ReportPropertyChanging("GPS_Lat");
                _GPS_Lat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GPS_Lat");
                OnGPS_LatChanged();
            }
        }
        private Nullable<global::System.Double> _GPS_Lat;
        partial void OnGPS_LatChanging(Nullable<global::System.Double> value);
        partial void OnGPS_LatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GPS_Long
        {
            get
            {
                return _GPS_Long;
            }
            set
            {
                OnGPS_LongChanging(value);
                ReportPropertyChanging("GPS_Long");
                _GPS_Long = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GPS_Long");
                OnGPS_LongChanged();
            }
        }
        private Nullable<global::System.Double> _GPS_Long;
        partial void OnGPS_LongChanging(Nullable<global::System.Double> value);
        partial void OnGPS_LongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Effective_Date
        {
            get
            {
                return _Effective_Date;
            }
            set
            {
                OnEffective_DateChanging(value);
                ReportPropertyChanging("Effective_Date");
                _Effective_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Effective_Date");
                OnEffective_DateChanged();
            }
        }
        private global::System.DateTime _Effective_Date;
        partial void OnEffective_DateChanging(global::System.DateTime value);
        partial void OnEffective_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Cease_Date
        {
            get
            {
                return _Cease_Date;
            }
            set
            {
                OnCease_DateChanging(value);
                ReportPropertyChanging("Cease_Date");
                _Cease_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cease_Date");
                OnCease_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Cease_Date;
        partial void OnCease_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnCease_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link_Address
        {
            get
            {
                return _Link_Address;
            }
            set
            {
                OnLink_AddressChanging(value);
                ReportPropertyChanging("Link_Address");
                _Link_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link_Address");
                OnLink_AddressChanged();
            }
        }
        private global::System.String _Link_Address;
        partial void OnLink_AddressChanging(global::System.String value);
        partial void OnLink_AddressChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Stockist2Location", "Stockist_Locations")]
        public Stockist_Locations Stockist_Locations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stockist_Locations>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist_Locations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stockist_Locations>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist_Locations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stockist_Locations> Stockist_LocationsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stockist_Locations>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist_Locations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stockist_Locations>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist_Locations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobynsHandMadeSoapModel", Name="Stockist_Locations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stockist_Locations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stockist_Locations object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="effective_Date">Initial value of the Effective_Date property.</param>
        public static Stockist_Locations CreateStockist_Locations(global::System.Int32 id, global::System.String name, global::System.DateTime effective_Date)
        {
            Stockist_Locations stockist_Locations = new Stockist_Locations();
            stockist_Locations.Id = id;
            stockist_Locations.Name = name;
            stockist_Locations.Effective_Date = effective_Date;
            return stockist_Locations;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Effective_Date
        {
            get
            {
                return _Effective_Date;
            }
            set
            {
                OnEffective_DateChanging(value);
                ReportPropertyChanging("Effective_Date");
                _Effective_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Effective_Date");
                OnEffective_DateChanged();
            }
        }
        private global::System.DateTime _Effective_Date;
        partial void OnEffective_DateChanging(global::System.DateTime value);
        partial void OnEffective_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Cease_Date
        {
            get
            {
                return _Cease_Date;
            }
            set
            {
                OnCease_DateChanging(value);
                ReportPropertyChanging("Cease_Date");
                _Cease_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cease_Date");
                OnCease_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Cease_Date;
        partial void OnCease_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnCease_DateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobynsHandMadeSoapModel", "FK_Stockist2Location", "Stockist")]
        public EntityCollection<Stockist> Stockists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stockist>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stockist>("RobynsHandMadeSoapModel.FK_Stockist2Location", "Stockist", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
